name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make all
      env:
        EPIC4_PATH: ~/epic
        MPI_TYPE: openmpi
        MACHINE_TYPE: LINUX
        EPIC_CC: gcc
        EPIC_CFLAG: -g
        EPIC_PRECISION: 8
      working-directory: ./src
      run: make all
